[colors.primary]
background = "#0c1115"
foreground = "#ffffff"

[colors.cursor]
text = "#0c1115"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#0c1115"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#0c1115"
background = "#ffffff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#999992"
background = "#ffffff"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c1115"
red = "#576653"
green = "#616B5D"
yellow = "#6C726D"
blue = "#78846E"
magenta = "#83867A"
cyan = "#9C9D96"
white = "#dbdbd1"

[colors.bright]
black = "#999992"
red = "#899b84"
green = "#949e90"
yellow = "#9fa5a0"
blue = "#abb4a4"
magenta = "#b5b7af"
cyan = "#cececb"
white = "#ffffff"

[colors.dim]
black = "#ffffff"
red = "#899b84"
green = "#949e90"
yellow = "#9fa5a0"
blue = "#abb4a4"
magenta = "#b5b7af"
cyan = "#cececb"
white = "#999992"
